import requests
import pprint
import json

ENTITY_UNSPECIFIED		 = 0
ENTITY_OTHER			 = 1
ENTITY_UNKNOWN			 = 2
ENTITY_PROCESSOR		 = 3
ENTITY_DISK			 = 4
ENTITY_PERIPHERAL		 = 5
ENTITY_SYSTEM_MANAGEMENT_MODULE	 = 6
ENTITY_SYSTEM_BOARD		 = 7
ENTITY_MEMORY_MODULE		 = 8
ENTITY_PROCESSOR_MODULE		 = 9
ENTITY_POWER_SUPPLY		 = 10
ENTITY_ADD_IN_CARD		 = 11
ENTITY_FRONT_PANEL_BOARD	 = 12
ENTITY_BACK_PANEL_BOARD		 = 13
ENTITY_POWER_SYS_BOARD		 = 14
ENTITY_DRIVE_BACKPLANE		 = 15
ENTITY_SYS_INTERNAL_EXP_BOARD	 = 16
ENTITY_OTHER_SYSTEM_BOARD	 = 17
ENTITY_PROCESSOR_BOARD		 = 18
ENTITY_POWER_UNIT		 = 19
ENTITY_POWER_MODULE		 = 20
ENTITY_POWER_MANAGEMENT_BOARD	 = 21
ENTITY_CHASSIS_BACK_PANEL_BOARD	 = 22
ENTITY_SYSTEM_CHASSIS		 = 23
ENTITY_SUB_CHASSIS		 = 24
ENTITY_OTHER_CHASSIS_BOARD	 = 25
ENTITY_DISK_DRIVE_BAY		 = 26
ENTITY_PERIPHERAL_BAY		 = 27
ENTITY_DEVICE_BAY		 = 28
ENTITY_FAN_COOLING		 = 29
ENTITY_COOLING_UNIT		 = 30
ENTITY_CABLE_INTERCONNECT	 = 31
ENTITY_MEMORY_DEVICE		 = 32
ENTITY_SYSTEM_MANAGEMENT_SW	 = 33
ENTITY_BIOS			 = 34
ENTITY_OPERATING_SYSTEM		 = 35
ENTITY_SYSTEM_BUS		 = 36
ENTITY_GROUP			 = 37
ENTITY_REMOTE_MANAGEMENT_DEVICE	 = 38
ENTITY_EXTERNAL_ENVIROMENT	 = 39
ENTITY_BATTERY			 = 40
ENTITY_PROCESSING_BLADE		 = 41
ENTITY_CONNECTIVITY_SWITCH	 = 42
ENTITY_PROCESSOR_MEMORY_MODULE	 = 43
ENTITY_IO_MODULE		 = 44
ENTITY_PROCESSOR_IO_MODULE	 = 45
ENTITY_MANAGEMENT_CONTROLLER_FW	 = 46

TYPE_OBJECT	    = 0x1
TYPE_TEMPERATURE    = 0x2
TYPE_AVERAGEPOWER   = 0x3
TYPE_MAXPOWER	    = 0x4
TYPE_INITFANDUTY    = 0x5
TYPE_FANDUTY	    = 0x6
TYPE_DEVICEFANMAP   = 0x7

TYPE_RSP_OK	    = 0x0
TYPE_RSP_ERROR	    = 0xF0
TYPE_CMD	    = 0x80

def http_request(url, payload):
    hds = {'content-type':'application/json; charset=utf-8', 'user-agent':'iopc-app'}
    rsp=requests.post(url, headers=hds, data=payload)
    return rsp

def response_output(out_format, rsp):
    if rsp.status_code == 200 :
        pprint.pprint(rsp.json())

def help_usage():
    print "hwmon.py <hostname>"
    sys.exit(1)

